name: Deploy to Development

#auto run on push to master
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run package-for-dev
      - name: Archive build
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist_dev
          path: dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist_dev
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa jordansportfolio.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.FTP_PRIVATE_KEY }}"
      - name: Deploy to Dev
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ls -a deploy_dist_dev/JordanAndDana
          ssh ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }} "cd ${{ secrets.FTP_REMOTE_PATH_DEV }} && rm -rf ./*"
          scp -r deploy_dist_dev/JordanAndDana* deploy_dist_dev/JordanAndDana/.htaccess ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_HOST }}:${{ secrets.FTP_REMOTE_PATH_DEV }}